// This file is generated by bench2vlog.py by littleshamoo
//   options: -t lst 
module s27 (CK, test_si, test_so, test_se, G0, G1, G2, G3, G17);

input G0;
input G1;
input G2;
input G3;
input CK;
input test_si;
input test_se;

output G17;
output test_so;

INVX1 U_G14( .A(G0), .Y(G14) );
INVX1 U_G17( .A(G11), .Y(G17) );
AND2XL U_G8( .A(G14), .B(G6), .Y(G8) );
OR2XL U_G15( .A(G12), .B(G8), .Y(G15) );
OR2XL U_G16( .A(G3), .B(G8), .Y(G16) );
NAND2XL U_G9( .A(G16), .B(G15), .Y(G9) );
NOR2XL U_G10( .A(G14), .B(G11), .Y(G10) );
NOR2XL U_G11( .A(G5), .B(G9), .Y(G11) );
NOR2XL U_G12( .A(G1), .B(G7), .Y(G12) );
NOR2XL U_G13( .A(G2), .B(G12), .Y(G13) );
SDFFXL U_G5 ( .SI(test_si), .SE(test_se), .D(G10), .CK(CK), .Q(G5) );
SDFFXL U_G6 ( .SI(G5), .SE(test_se), .D(G11), .CK(CK), .Q(G6) );
SDFFXL U_G7 ( .SI(G6), .SE(test_se), .D(G13), .CK(CK), .Q(G7) );

assign test_so = G7;

endmodule
