#############################################################################
# File       [ Makefile ]
# Author     [ littleshamoo ]
# Synopsis   [ package makefile ]
# Date       [ 2010/10/07 created ]
#############################################################################

include ../../common.mk
include ../../info.mk
include ../../rule.mk

