/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s292_1
#  OS:                Linux x86_64(Host ID cad29)
#  Generated on:      Tue May  6 00:42:15 2014
#  Design:            s208
#  Command:           saveNetlist netlist_PR/s208/s208_placed.v
###############################################################
*/
module s208 (
	CK, 
	X, 
	Clear, 
	C_8, 
	C_7, 
	C_6, 
	C_5, 
	C_4, 
	C_3, 
	C_2, 
	C_1, 
	C_0, 
	test_se, 
	test_si, 
	W, 
	Z, 
	test_so);
   input CK;
   input X;
   input Clear;
   input C_8;
   input C_7;
   input C_6;
   input C_5;
   input C_4;
   input C_3;
   input C_2;
   input C_1;
   input C_0;
   input test_se;
   input test_si;
   output W;
   output Z;
   output test_so;

   // Internal wires
   wire II104;
   wire II6;
   wire II92;
   wire II50;
   wire II40;
   wire Y_4;
   wire II41;
   wire Y_3;
   wire II42;
   wire Y_2;
   wire II43;
   wire Y_1;
   wire II44;
   wire II46;
   wire II3;
   wire II47;
   wire II4;
   wire II256;
   wire II158;
   wire II244;
   wire II202;
   wire II1_1;
   wire II192;
   wire Y_8;
   wire II193;
   wire Y_7;
   wire II194;
   wire Y_6;
   wire II195;
   wire Y_5;
   wire II196;
   wire II198;
   wire II155;
   wire II199;
   wire II156;
   wire II341;
   wire II307_1;
   wire II314;
   wire P_1;
   wire II316;
   wire P_3;
   wire II317;
   wire P_4;
   wire II369;
   wire II374;
   wire P_6;
   wire II446;
   wire II488;
   wire II487;
   wire II490;
   wire II489;
   wire II109;
   wire II127_1;
   wire II96;
   wire II113;
   wire II127_2;
   wire II131_1;
   wire II131_2;
   wire II261;
   wire II279_1;
   wire II248;
   wire II265;
   wire II279_2;
   wire II283_1;
   wire II283_2;
   wire P_8;
   wire II497_1;
   wire P_5;
   wire II500_1;
   wire P_2;
   wire II500_2;
   wire II504_1;
   wire II504_2;
   wire II508_1;
   wire II508_2;
   wire II512_1;
   wire P_7;
   wire II512_2;
   wire II135_1;
   wire II100;
   wire II135_2;
   wire II287_1;
   wire II252;
   wire II287_2;
   wire II5;
   wire II157;
   wire II347;
   wire II350;
   wire II406;
   wire II378;
   wire II409;
   wire II484;
   wire II494;
   wire II495;

   assign test_so = Y_5 ;

   INV_X1 U_II6 (.ZN(II6), 
	.A(II104));
   INV_X1 U_II50 (.ZN(II50), 
	.A(II92));
   INV_X1 U_II40 (.ZN(II40), 
	.A(X));
   INV_X1 U_II41 (.ZN(II41), 
	.A(Y_4));
   INV_X1 U_II42 (.ZN(II42), 
	.A(Y_3));
   INV_X1 U_II43 (.ZN(II43), 
	.A(Y_2));
   INV_X1 U_II44 (.ZN(II44), 
	.A(Y_1));
   INV_X1 U_II3 (.ZN(II3), 
	.A(II46));
   INV_X1 U_II4 (.ZN(II4), 
	.A(II47));
   INV_X1 U_II158 (.ZN(II158), 
	.A(II256));
   INV_X1 U_II202 (.ZN(II202), 
	.A(II244));
   INV_X1 U_II192 (.ZN(II192), 
	.A(II1_1));
   INV_X1 U_II193 (.ZN(II193), 
	.A(Y_8));
   INV_X1 U_II194 (.ZN(II194), 
	.A(Y_7));
   INV_X1 U_II195 (.ZN(II195), 
	.A(Y_6));
   INV_X1 U_II196 (.ZN(II196), 
	.A(Y_5));
   INV_X1 U_II155 (.ZN(II155), 
	.A(II198));
   INV_X1 U_II156 (.ZN(II156), 
	.A(II199));
   INV_X1 U_II307_1 (.ZN(II307_1), 
	.A(II341));
   INV_X1 U_P_1 (.ZN(P_1), 
	.A(II314));
   INV_X1 U_P_3 (.ZN(P_3), 
	.A(II316));
   INV_X1 U_P_4 (.ZN(P_4), 
	.A(II317));
   INV_X1 U_II369 (.ZN(II369), 
	.A(Y_5));
   INV_X1 U_P_6 (.ZN(P_6), 
	.A(II374));
   INV_X1 U_Z (.ZN(Z), 
	.A(II446));
   INV_X1 U_II487 (.ZN(II487), 
	.A(II488));
   INV_X1 U_II489 (.ZN(II489), 
	.A(II490));
   AND3_X1 U_II127_1 (.ZN(II127_1), 
	.A3(II109), 
	.A2(Y_3), 
	.A1(II41));
   AND3_X1 U_II127_2 (.ZN(II127_2), 
	.A3(Y_4), 
	.A2(II113), 
	.A1(II96));
   AND3_X1 U_II131_1 (.ZN(II131_1), 
	.A3(Y_3), 
	.A2(II92), 
	.A1(II113));
   AND2_X1 U_II131_2 (.ZN(II131_2), 
	.A2(II109), 
	.A1(II42));
   AND3_X1 U_II279_1 (.ZN(II279_1), 
	.A3(II261), 
	.A2(Y_7), 
	.A1(II193));
   AND3_X1 U_II279_2 (.ZN(II279_2), 
	.A3(Y_8), 
	.A2(II265), 
	.A1(II248));
   AND3_X1 U_II283_1 (.ZN(II283_1), 
	.A3(Y_7), 
	.A2(II244), 
	.A1(II265));
   AND2_X1 U_II283_2 (.ZN(II283_2), 
	.A2(II261), 
	.A1(II194));
   AND2_X1 U_II497_1 (.ZN(II497_1), 
	.A2(C_8), 
	.A1(P_8));
   AND2_X1 U_II500_1 (.ZN(II500_1), 
	.A2(C_5), 
	.A1(P_5));
   AND2_X1 U_II500_2 (.ZN(II500_2), 
	.A2(C_2), 
	.A1(P_2));
   AND2_X1 U_II504_1 (.ZN(II504_1), 
	.A2(C_3), 
	.A1(P_3));
   AND2_X1 U_II504_2 (.ZN(II504_2), 
	.A2(C_4), 
	.A1(P_4));
   AND2_X1 U_II508_1 (.ZN(II508_1), 
	.A2(C_0), 
	.A1(X));
   AND2_X1 U_II508_2 (.ZN(II508_2), 
	.A2(C_1), 
	.A1(P_1));
   AND2_X1 U_II512_1 (.ZN(II512_1), 
	.A2(C_6), 
	.A1(P_6));
   AND2_X1 U_II512_2 (.ZN(II512_2), 
	.A2(C_7), 
	.A1(P_7));
   OR2_X1 U_II135_1 (.ZN(II135_1), 
	.A2(II104), 
	.A1(II43));
   OR2_X1 U_II135_2 (.ZN(II135_2), 
	.A2(II100), 
	.A1(Y_2));
   OR2_X1 U_II287_1 (.ZN(II287_1), 
	.A2(II256), 
	.A1(II195));
   OR2_X1 U_II287_2 (.ZN(II287_2), 
	.A2(II252), 
	.A1(Y_6));
   NAND2_X1 U_II5 (.ZN(II5), 
	.A2(II135_2), 
	.A1(II135_1));
   NAND2_X1 U_II92 (.ZN(II92), 
	.A2(Y_1), 
	.A1(Y_2));
   NAND2_X1 U_II96 (.ZN(II96), 
	.A2(II50), 
	.A1(Y_3));
   NAND2_X1 U_II100 (.ZN(II100), 
	.A2(II113), 
	.A1(Y_1));
   NAND2_X1 U_II104 (.ZN(II104), 
	.A2(II113), 
	.A1(II44));
   NAND2_X1 U_II157 (.ZN(II157), 
	.A2(II287_2), 
	.A1(II287_1));
   NAND2_X1 U_II244 (.ZN(II244), 
	.A2(Y_5), 
	.A1(Y_6));
   NAND2_X1 U_II248 (.ZN(II248), 
	.A2(II202), 
	.A1(Y_7));
   NAND2_X1 U_II252 (.ZN(II252), 
	.A2(II265), 
	.A1(Y_5));
   NAND2_X1 U_II256 (.ZN(II256), 
	.A2(II265), 
	.A1(II196));
   NAND2_X1 U_II314 (.ZN(II314), 
	.A2(Y_1), 
	.A1(X));
   NAND2_X1 U_II316 (.ZN(II316), 
	.A2(II347), 
	.A1(Y_3));
   NAND2_X1 U_II317 (.ZN(II317), 
	.A2(II307_1), 
	.A1(Y_4));
   NAND2_X1 U_II341 (.ZN(II341), 
	.A2(II347), 
	.A1(II42));
   NAND2_X1 U_II350 (.ZN(II350), 
	.A2(II44), 
	.A1(X));
   NAND2_X1 U_II374 (.ZN(II374), 
	.A2(II406), 
	.A1(Y_6));
   NAND2_X1 U_II378 (.ZN(II378), 
	.A2(II195), 
	.A1(II406));
   NAND2_X1 U_II409 (.ZN(II409), 
	.A2(II307_1), 
	.A1(II41));
   NAND2_X1 U_II495 (.ZN(II495), 
	.A2(II494), 
	.A1(II484));
   NOR2_X1 U_II1_1 (.ZN(II1_1), 
	.A2(II96), 
	.A1(II41));
   NOR2_X1 U_II46 (.ZN(II46), 
	.A2(II127_2), 
	.A1(II127_1));
   NOR2_X1 U_II47 (.ZN(II47), 
	.A2(II131_2), 
	.A1(II131_1));
   NOR2_X1 U_II109 (.ZN(II109), 
	.A2(II100), 
	.A1(II43));
   NOR2_X1 U_II113 (.ZN(II113), 
	.A2(II40), 
	.A1(Clear));
   NOR2_X1 U_W (.ZN(W), 
	.A2(II248), 
	.A1(II193));
   NOR2_X1 U_II198 (.ZN(II198), 
	.A2(II279_2), 
	.A1(II279_1));
   NOR2_X1 U_II199 (.ZN(II199), 
	.A2(II283_2), 
	.A1(II283_1));
   NOR2_X1 U_II261 (.ZN(II261), 
	.A2(II252), 
	.A1(II195));
   NOR2_X1 U_II265 (.ZN(II265), 
	.A2(II192), 
	.A1(Clear));
   NOR2_X1 U_P_2 (.ZN(P_2), 
	.A2(II350), 
	.A1(II43));
   NOR2_X1 U_II347 (.ZN(II347), 
	.A2(II350), 
	.A1(Y_2));
   NOR2_X1 U_P_5 (.ZN(P_5), 
	.A2(II409), 
	.A1(II369));
   NOR2_X1 U_P_7 (.ZN(P_7), 
	.A2(II378), 
	.A1(II194));
   NOR3_X1 U_P_8 (.ZN(P_8), 
	.A3(II193), 
	.A2(II378), 
	.A1(Y_7));
   NOR2_X1 U_II406 (.ZN(II406), 
	.A2(Y_5), 
	.A1(II409));
   NOR3_X1 U_II446 (.ZN(II446), 
	.A3(II497_1), 
	.A2(II487), 
	.A1(II495));
   NOR2_X1 U_II484 (.ZN(II484), 
	.A2(II500_2), 
	.A1(II500_1));
   NOR2_X1 U_II488 (.ZN(II488), 
	.A2(II504_2), 
	.A1(II504_1));
   NOR2_X1 U_II490 (.ZN(II490), 
	.A2(II508_2), 
	.A1(II508_1));
   NOR3_X1 U_II494 (.ZN(II494), 
	.A3(II489), 
	.A2(II512_2), 
	.A1(II512_1));
   SDFF_X1 U_Y_4 (.SI(test_si), 
	.SE(test_se), 
	.Q(Y_4), 
	.D(II3), 
	.CK(CK));
   SDFF_X1 U_Y_3 (.SI(Y_4), 
	.SE(test_se), 
	.Q(Y_3), 
	.D(II4), 
	.CK(CK));
   SDFF_X1 U_Y_2 (.SI(Y_3), 
	.SE(test_se), 
	.Q(Y_2), 
	.D(II5), 
	.CK(CK));
   SDFF_X1 U_Y_1 (.SI(Y_2), 
	.SE(test_se), 
	.Q(Y_1), 
	.D(II6), 
	.CK(CK));
   SDFF_X1 U_Y_8 (.SI(Y_1), 
	.SE(test_se), 
	.Q(Y_8), 
	.D(II155), 
	.CK(CK));
   SDFF_X1 U_Y_7 (.SI(Y_8), 
	.SE(test_se), 
	.Q(Y_7), 
	.D(II156), 
	.CK(CK));
   SDFF_X1 U_Y_6 (.SI(Y_7), 
	.SE(test_se), 
	.Q(Y_6), 
	.D(II157), 
	.CK(CK));
   SDFF_X1 U_Y_5 (.SI(Y_6), 
	.SE(test_se), 
	.Q(Y_5), 
	.D(II158), 
	.CK(CK));
endmodule

