/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s292_1
#  OS:                Linux x86_64(Host ID cad29)
#  Generated on:      Tue May  6 00:44:48 2014
#  Design:            s27
#  Command:           saveNetlist netlist_PR/s27/s27_placed.v
###############################################################
*/
module s27 (
	CK, 
	G0, 
	G1, 
	G2, 
	G3, 
	test_se, 
	test_si, 
	G17, 
	test_so);
   input CK;
   input G0;
   input G1;
   input G2;
   input G3;
   input test_se;
   input test_si;
   output G17;
   output test_so;

   // Internal wires
   wire G14;
   wire G11;
   wire G6;
   wire G8;
   wire G12;
   wire G15;
   wire G16;
   wire G9;
   wire G10;
   wire G5;
   wire G7;
   wire G13;

   assign test_so = G7 ;

   INV_X1 U_G14 (.ZN(G14), 
	.A(G0));
   INV_X1 U_G17 (.ZN(G17), 
	.A(G11));
   AND2_X1 U_G8 (.ZN(G8), 
	.A2(G6), 
	.A1(G14));
   OR2_X1 U_G15 (.ZN(G15), 
	.A2(G8), 
	.A1(G12));
   OR2_X1 U_G16 (.ZN(G16), 
	.A2(G8), 
	.A1(G3));
   NAND2_X1 U_G9 (.ZN(G9), 
	.A2(G15), 
	.A1(G16));
   NOR2_X1 U_G10 (.ZN(G10), 
	.A2(G11), 
	.A1(G14));
   NOR2_X1 U_G11 (.ZN(G11), 
	.A2(G9), 
	.A1(G5));
   NOR2_X1 U_G12 (.ZN(G12), 
	.A2(G7), 
	.A1(G1));
   NOR2_X1 U_G13 (.ZN(G13), 
	.A2(G12), 
	.A1(G2));
   SDFF_X1 U_G5 (.SI(test_si), 
	.SE(test_se), 
	.Q(G5), 
	.D(G10), 
	.CK(CK));
   SDFF_X1 U_G6 (.SI(G5), 
	.SE(test_se), 
	.Q(G6), 
	.D(G11), 
	.CK(CK));
   SDFF_X1 U_G7 (.SI(G6), 
	.SE(test_se), 
	.Q(G7), 
	.D(G13), 
	.CK(CK));
endmodule

