/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s292_1
#  OS:                Linux x86_64(Host ID cad29)
#  Generated on:      Tue May  6 01:48:20 2014
#  Design:            s510
#  Command:           saveNetlist netlist_PR/s510/s510_placed.v
###############################################################
*/
module s510 (
	CK, 
	john, 
	cnt13, 
	cnt21, 
	cnt284, 
	pcnt6, 
	cnt261, 
	cnt44, 
	pcnt12, 
	pcnt17, 
	cnt591, 
	cnt45, 
	cnt567, 
	pcnt27, 
	cnt283, 
	cnt272, 
	cnt10, 
	cnt511, 
	pcnt241, 
	cnt509, 
	test_se, 
	test_si, 
	csm, 
	pclr, 
	pc, 
	cclr, 
	vsync, 
	cblank, 
	csync, 
	test_so);
   input CK;
   input john;
   input cnt13;
   input cnt21;
   input cnt284;
   input pcnt6;
   input cnt261;
   input cnt44;
   input pcnt12;
   input pcnt17;
   input cnt591;
   input cnt45;
   input cnt567;
   input pcnt27;
   input cnt283;
   input cnt272;
   input cnt10;
   input cnt511;
   input pcnt241;
   input cnt509;
   input test_se;
   input test_si;
   output csm;
   output pclr;
   output pc;
   output cclr;
   output vsync;
   output cblank;
   output csync;
   output test_so;

   // Internal wires
   wire I68;
   wire I67;
   wire I78;
   wire I73;
   wire st_0;
   wire I61;
   wire st_1;
   wire I60;
   wire st_2;
   wire I59;
   wire st_3;
   wire I58;
   wire st_4;
   wire I57;
   wire st_5;
   wire I56;
   wire I69;
   wire I70;
   wire I555;
   wire I554;
   wire I590;
   wire I591;
   wire I595;
   wire I594;
   wire I547;
   wire I546;
   wire I666;
   wire I667;
   wire I474;
   wire I475;
   wire I799;
   wire I798;
   wire I494;
   wire I495;
   wire I466;
   wire I467;
   wire I463;
   wire I462;
   wire I131;
   wire I130;
   wire I566;
   wire I567;
   wire I482;
   wire I483;
   wire I531;
   wire I530;
   wire I487;
   wire I486;
   wire I606;
   wire I607;
   wire I779;
   wire I778;
   wire I346;
   wire I347;
   wire I205;
   wire I204;
   wire I217;
   wire I216;
   wire I936_2;
   wire I946_1;
   wire I946_2;
   wire I936_1;
   wire I1089_1;
   wire I1044_1;
   wire I578;
   wire I943_1;
   wire I675;
   wire I1102_2;
   wire I671;
   wire I1059_1;
   wire I551;
   wire I1071_1;
   wire I1106_1;
   wire I663;
   wire I1123_1;
   wire I498;
   wire I967_1;
   wire I570;
   wire I1055_1;
   wire I535;
   wire I598;
   wire I1062_1;
   wire I795;
   wire I618;
   wire I1120_1;
   wire I95;
   wire I603;
   wire I1116_1;
   wire I950_2;
   wire I455;
   wire I950_1;
   wire I1102_1;
   wire I587;
   wire I104;
   wire I954_2;
   wire I543;
   wire I490;
   wire I1081_1;
   wire I1106_2;
   wire I940_1;
   wire I539;
   wire I1077_1;
   wire I694;
   wire I698;
   wire I988_1;
   wire I787;
   wire I1085_1;
   wire I954_1;
   wire I1081_2;
   wire I230;
   wire I1116_2;
   wire I232;
   wire I1065_1;
   wire I234;
   wire I1113_1;
   wire I1055_2;
   wire I1085_2;
   wire I1038_1;
   wire I985_1;
   wire I914_1;
   wire I1068_1;
   wire I933_1;
   wire I958_1;
   wire I642;
   wire I958_2;
   wire I924_2;
   wire I478;
   wire I903_2;
   wire I1092_1;
   wire I458;
   wire I917_1;
   wire I921_1;
   wire I627;
   wire I909_1;
   wire I962_2;
   wire I506;
   wire I1095_1;
   wire I209;
   wire I1099_1;
   wire I917_2;
   wire I559;
   wire I982_1;
   wire I1074_1;
   wire I1095_2;
   wire I970_1;
   wire I207;
   wire I900_1;
   wire I742;
   wire I903_1;
   wire I962_1;
   wire I975_1;
   wire I747;
   wire I978_1;
   wire I928_1;
   wire I1110_1;
   wire I731;
   wire I924_1;
   wire I658;
   wire I814;
   wire I574;
   wire I511;
   wire I638;
   wire I739;
   wire I774;
   wire I583;
   wire I390;
   wire I834;
   wire I563;
   wire I274;
   wire I810;
   wire I782;
   wire I870;
   wire I298;
   wire I710;
   wire I714;
   wire I326;
   wire I837;
   wire I615;
   wire I270;
   wire I838;
   wire I872;
   wire I266;
   wire I877;
   wire I213;
   wire I278;
   wire I282;
   wire I823;
   wire I3;
   wire I855;
   wire I867;
   wire I841;
   wire I4;
   wire I861;
   wire I884;
   wire I889;
   wire I827;
   wire I5;
   wire I881;
   wire I899;
   wire I895;
   wire I6;
   wire I821;
   wire I2;
   wire I863;
   wire I831;
   wire I874;
   wire I887;
   wire I7;
   wire I259;
   wire I371;

   assign test_so = st_0 ;

   INV_X1 U_I68 (.ZN(I68), 
	.A(cnt44));
   INV_X1 U_I67 (.ZN(I67), 
	.A(cnt261));
   INV_X1 U_I78 (.ZN(I78), 
	.A(cnt511));
   INV_X1 U_I73 (.ZN(I73), 
	.A(cnt567));
   INV_X1 U_I61 (.ZN(I61), 
	.A(st_0));
   INV_X1 U_I60 (.ZN(I60), 
	.A(st_1));
   INV_X1 U_I59 (.ZN(I59), 
	.A(st_2));
   INV_X1 U_I58 (.ZN(I58), 
	.A(st_3));
   INV_X1 U_I57 (.ZN(I57), 
	.A(st_4));
   INV_X1 U_I56 (.ZN(I56), 
	.A(st_5));
   INV_X1 U_I69 (.ZN(I69), 
	.A(pcnt12));
   INV_X1 U_I70 (.ZN(I70), 
	.A(pcnt17));
   INV_X1 U_I554 (.ZN(I554), 
	.A(I555));
   INV_X1 U_I591 (.ZN(I591), 
	.A(I590));
   INV_X1 U_I594 (.ZN(I594), 
	.A(I595));
   INV_X1 U_I546 (.ZN(I546), 
	.A(I547));
   INV_X1 U_I667 (.ZN(I667), 
	.A(I666));
   INV_X1 U_I475 (.ZN(I475), 
	.A(I474));
   INV_X1 U_I798 (.ZN(I798), 
	.A(I799));
   INV_X1 U_I495 (.ZN(I495), 
	.A(I494));
   INV_X1 U_I467 (.ZN(I467), 
	.A(I466));
   INV_X1 U_I462 (.ZN(I462), 
	.A(I463));
   INV_X1 U_I130 (.ZN(I130), 
	.A(I131));
   INV_X1 U_I567 (.ZN(I567), 
	.A(I566));
   INV_X1 U_I483 (.ZN(I483), 
	.A(I482));
   INV_X1 U_I530 (.ZN(I530), 
	.A(I531));
   INV_X1 U_I486 (.ZN(I486), 
	.A(I487));
   INV_X1 U_I607 (.ZN(I607), 
	.A(I606));
   INV_X1 U_I778 (.ZN(I778), 
	.A(I779));
   INV_X1 U_I347 (.ZN(I347), 
	.A(I346));
   INV_X1 U_I204 (.ZN(I204), 
	.A(I205));
   INV_X1 U_I216 (.ZN(I216), 
	.A(I217));
   AND2_X1 U_I936_2 (.ZN(I936_2), 
	.A2(st_2), 
	.A1(cnt272));
   AND2_X1 U_I946_1 (.ZN(I946_1), 
	.A2(st_5), 
	.A1(cnt10));
   AND2_X1 U_I946_2 (.ZN(I946_2), 
	.A2(st_4), 
	.A1(john));
   AND2_X1 U_I936_1 (.ZN(I936_1), 
	.A2(I59), 
	.A1(cnt591));
   AND2_X1 U_I1089_1 (.ZN(I1089_1), 
	.A2(I555), 
	.A1(I59));
   AND2_X1 U_I1044_1 (.ZN(I1044_1), 
	.A2(cnt284), 
	.A1(I70));
   AND2_X1 U_I943_1 (.ZN(I943_1), 
	.A2(st_3), 
	.A1(I578));
   AND2_X1 U_I1102_2 (.ZN(I1102_2), 
	.A2(I675), 
	.A1(I56));
   AND2_X1 U_I1059_1 (.ZN(I1059_1), 
	.A2(I671), 
	.A1(st_5));
   AND2_X1 U_I1071_1 (.ZN(I1071_1), 
	.A2(I671), 
	.A1(I551));
   AND2_X1 U_I1106_1 (.ZN(I1106_1), 
	.A2(I551), 
	.A1(I60));
   AND2_X1 U_I1123_1 (.ZN(I1123_1), 
	.A2(I663), 
	.A1(I551));
   AND2_X1 U_I967_1 (.ZN(I967_1), 
	.A2(I57), 
	.A1(I498));
   AND3_X1 U_I1055_1 (.ZN(I1055_1), 
	.A3(st_2), 
	.A2(st_0), 
	.A1(I570));
   AND2_X1 U_I1062_1 (.ZN(I1062_1), 
	.A2(I598), 
	.A1(I535));
   AND2_X1 U_I1120_1 (.ZN(I1120_1), 
	.A2(I618), 
	.A1(I795));
   AND2_X1 U_I1116_1 (.ZN(I1116_1), 
	.A2(I603), 
	.A1(I95));
   AND2_X1 U_I950_2 (.ZN(I950_2), 
	.A2(cnt283), 
	.A1(I463));
   AND2_X1 U_I950_1 (.ZN(I950_1), 
	.A2(cnt45), 
	.A1(I455));
   AND2_X1 U_I1102_1 (.ZN(I1102_1), 
	.A2(I455), 
	.A1(st_5));
   AND3_X1 U_I954_2 (.ZN(I954_2), 
	.A3(I104), 
	.A2(I587), 
	.A1(cnt45));
   AND3_X1 U_I1081_1 (.ZN(I1081_1), 
	.A3(I58), 
	.A2(I490), 
	.A1(I543));
   AND2_X1 U_I1106_2 (.ZN(I1106_2), 
	.A2(I543), 
	.A1(I57));
   AND2_X1 U_I940_1 (.ZN(I940_1), 
	.A2(I60), 
	.A1(I495));
   AND2_X1 U_I1077_1 (.ZN(I1077_1), 
	.A2(I539), 
	.A1(I104));
   AND2_X1 U_I988_1 (.ZN(I988_1), 
	.A2(I698), 
	.A1(I694));
   AND2_X1 U_I1085_1 (.ZN(I1085_1), 
	.A2(I130), 
	.A1(I787));
   AND3_X1 U_I954_1 (.ZN(I954_1), 
	.A3(I567), 
	.A2(cnt509), 
	.A1(st_5));
   AND2_X1 U_I1081_2 (.ZN(I1081_2), 
	.A2(I483), 
	.A1(st_2));
   AND2_X1 U_I1116_2 (.ZN(I1116_2), 
	.A2(I230), 
	.A1(I61));
   AND2_X1 U_I1065_1 (.ZN(I1065_1), 
	.A2(I232), 
	.A1(I475));
   AND2_X1 U_I1113_1 (.ZN(I1113_1), 
	.A2(I234), 
	.A1(st_4));
   AND2_X1 U_I1055_2 (.ZN(I1055_2), 
	.A2(I204), 
	.A1(I58));
   AND2_X1 U_I1085_2 (.ZN(I1085_2), 
	.A2(I216), 
	.A1(I61));
   OR2_X1 U_I1038_1 (.ZN(I1038_1), 
	.A2(st_0), 
	.A1(cnt21));
   OR2_X1 U_I985_1 (.ZN(I985_1), 
	.A2(I73), 
	.A1(pcnt27));
   OR2_X1 U_I914_1 (.ZN(I914_1), 
	.A2(I61), 
	.A1(I60));
   OR2_X1 U_I1068_1 (.ZN(I1068_1), 
	.A2(I590), 
	.A1(st_4));
   OR2_X1 U_I933_1 (.ZN(I933_1), 
	.A2(I58), 
	.A1(I57));
   OR2_X1 U_I958_1 (.ZN(I958_1), 
	.A2(I59), 
	.A1(I57));
   OR2_X1 U_I958_2 (.ZN(I958_2), 
	.A2(I642), 
	.A1(cnt284));
   OR2_X1 U_I924_2 (.ZN(I924_2), 
	.A2(I666), 
	.A1(I474));
   OR2_X1 U_I903_2 (.ZN(I903_2), 
	.A2(I478), 
	.A1(I58));
   OR2_X1 U_I1092_1 (.ZN(I1092_1), 
	.A2(I478), 
	.A1(st_4));
   OR3_X1 U_I917_1 (.ZN(I917_1), 
	.A3(st_5), 
	.A2(I494), 
	.A1(I458));
   OR2_X1 U_I921_1 (.ZN(I921_1), 
	.A2(I570), 
	.A1(I494));
   OR2_X1 U_I909_1 (.ZN(I909_1), 
	.A2(I627), 
	.A1(I466));
   OR2_X1 U_I962_2 (.ZN(I962_2), 
	.A2(I78), 
	.A1(I466));
   OR2_X1 U_I1095_1 (.ZN(I1095_1), 
	.A2(I506), 
	.A1(cnt13));
   OR2_X1 U_I1099_1 (.ZN(I1099_1), 
	.A2(I209), 
	.A1(I506));
   OR2_X1 U_I917_2 (.ZN(I917_2), 
	.A2(I590), 
	.A1(I482));
   OR2_X1 U_I982_1 (.ZN(I982_1), 
	.A2(I487), 
	.A1(I559));
   OR2_X1 U_I1074_1 (.ZN(I1074_1), 
	.A2(I546), 
	.A1(I475));
   OR2_X1 U_I1095_2 (.ZN(I1095_2), 
	.A2(I578), 
	.A1(I475));
   OR2_X1 U_I970_1 (.ZN(I970_1), 
	.A2(I603), 
	.A1(I495));
   OR2_X1 U_I900_1 (.ZN(I900_1), 
	.A2(I207), 
	.A1(I56));
   OR2_X1 U_I903_1 (.ZN(I903_1), 
	.A2(I742), 
	.A1(I606));
   OR2_X1 U_I962_1 (.ZN(I962_1), 
	.A2(I73), 
	.A1(I462));
   OR2_X1 U_I975_1 (.ZN(I975_1), 
	.A2(I483), 
	.A1(I531));
   OR2_X1 U_I978_1 (.ZN(I978_1), 
	.A2(I747), 
	.A1(I483));
   OR2_X1 U_I928_1 (.ZN(I928_1), 
	.A2(I530), 
	.A1(st_0));
   OR2_X1 U_I1110_1 (.ZN(I1110_1), 
	.A2(I530), 
	.A1(I61));
   OR2_X1 U_I924_1 (.ZN(I924_1), 
	.A2(I731), 
	.A1(st_0));
   NAND2_X1 U_I590 (.ZN(I590), 
	.A2(st_2), 
	.A1(st_1));
   NAND2_X1 U_I458 (.ZN(I458), 
	.A2(st_1), 
	.A1(st_3));
   NAND2_X1 U_I490 (.ZN(I490), 
	.A2(pcnt17), 
	.A1(cnt284));
   NAND2_X1 U_I578 (.ZN(I578), 
	.A2(st_1), 
	.A1(I61));
   NAND2_X1 U_I666 (.ZN(I666), 
	.A2(st_3), 
	.A1(I61));
   NAND2_X1 U_I658 (.ZN(I658), 
	.A2(I58), 
	.A1(st_2));
   NAND3_X1 U_I814 (.ZN(I814), 
	.A3(I595), 
	.A2(cnt21), 
	.A1(I58));
   NAND2_X1 U_I574 (.ZN(I574), 
	.A2(I57), 
	.A1(st_3));
   NAND2_X1 U_I498 (.ZN(I498), 
	.A2(I587), 
	.A1(I511));
   NAND2_X1 U_I638 (.ZN(I638), 
	.A2(st_0), 
	.A1(I511));
   NAND2_X1 U_I642 (.ZN(I642), 
	.A2(st_2), 
	.A1(I739));
   NAND2_X1 U_I474 (.ZN(I474), 
	.A2(I57), 
	.A1(I56));
   NAND2_X1 U_I570 (.ZN(I570), 
	.A2(I56), 
	.A1(I458));
   NAND2_X1 U_I598 (.ZN(I598), 
	.A2(I56), 
	.A1(cnt13));
   NAND2_X1 U_I742 (.ZN(I742), 
	.A2(st_0), 
	.A1(I56));
   NAND2_X1 U_I618 (.ZN(I618), 
	.A2(cnt44), 
	.A1(I69));
   NAND2_X1 U_I478 (.ZN(I478), 
	.A2(I739), 
	.A1(I547));
   NAND2_X1 U_I494 (.ZN(I494), 
	.A2(I547), 
	.A1(I57));
   NAND3_X1 U_I774 (.ZN(I774), 
	.A3(I458), 
	.A2(I547), 
	.A1(st_5));
   NAND2_X1 U_I466 (.ZN(I466), 
	.A2(I535), 
	.A1(st_3));
   NAND2_X1 U_I506 (.ZN(I506), 
	.A2(I58), 
	.A1(I535));
   NAND2_X1 U_I566 (.ZN(I566), 
	.A2(st_2), 
	.A1(I663));
   NAND2_X1 U_I104 (.ZN(I104), 
	.A2(I56), 
	.A1(I933_1));
   NAND2_X1 U_I482 (.ZN(I482), 
	.A2(I551), 
	.A1(I58));
   NAND2_X1 U_I390 (.ZN(I390), 
	.A2(I583), 
	.A1(st_0));
   NAND2_X1 U_I834 (.ZN(I834), 
	.A2(I642), 
	.A1(I1068_1));
   NAND2_X1 U_I698 (.ZN(I698), 
	.A2(I59), 
	.A1(I563));
   NAND2_X1 U_I694 (.ZN(I694), 
	.A2(I57), 
	.A1(I795));
   NAND2_X1 U_I274 (.ZN(I274), 
	.A2(I667), 
	.A1(I56));
   NAND2_X1 U_I606 (.ZN(I606), 
	.A2(I57), 
	.A1(I95));
   NAND2_X1 U_I346 (.ZN(I346), 
	.A2(I463), 
	.A1(I985_1));
   NAND3_X1 U_I810 (.ZN(I810), 
	.A3(I455), 
	.A2(cnt284), 
	.A1(pcnt6));
   NAND3_X1 U_I782 (.ZN(I782), 
	.A3(I675), 
	.A2(I559), 
	.A1(I67));
   NAND2_X1 U_I230 (.ZN(I230), 
	.A2(I958_2), 
	.A1(I958_1));
   NAND2_X1 U_I870 (.ZN(I870), 
	.A2(I566), 
	.A1(I1092_1));
   NAND2_X1 U_I298 (.ZN(I298), 
	.A2(I574), 
	.A1(I539));
   NAND2_X1 U_I710 (.ZN(I710), 
	.A2(cnt10), 
	.A1(I467));
   NAND2_X1 U_I714 (.ZN(I714), 
	.A2(I567), 
	.A1(I1038_1));
   NAND2_X1 U_pclr (.ZN(pclr), 
	.A2(I917_2), 
	.A1(I917_1));
   NAND2_X1 U_I326 (.ZN(I326), 
	.A2(I61), 
	.A1(I982_1));
   NAND2_X1 U_pc (.ZN(pc), 
	.A2(I837), 
	.A1(I921_1));
   NAND2_X1 U_I270 (.ZN(I270), 
	.A2(I615), 
	.A1(st_3));
   NAND2_X1 U_I838 (.ZN(I838), 
	.A2(I530), 
	.A1(I1074_1));
   NAND3_X1 U_I872 (.ZN(I872), 
	.A3(I774), 
	.A2(I1095_2), 
	.A1(I1095_1));
   NAND2_X1 U_I266 (.ZN(I266), 
	.A2(st_1), 
	.A1(I970_1));
   NAND3_X1 U_I232 (.ZN(I232), 
	.A3(I810), 
	.A2(I962_2), 
	.A1(I962_1));
   NAND4_X1 U_cclr (.ZN(cclr), 
	.A4(I390), 
	.A3(I546), 
	.A2(I877), 
	.A1(I486));
   NAND4_X1 U_I234 (.ZN(I234), 
	.A4(I714), 
	.A3(I710), 
	.A2(I814), 
	.A1(I213));
   NAND2_X1 U_I278 (.ZN(I278), 
	.A2(I60), 
	.A1(I975_1));
   NAND2_X1 U_I282 (.ZN(I282), 
	.A2(st_1), 
	.A1(I978_1));
   NAND3_X1 U_I3 (.ZN(I3), 
	.A3(I823), 
	.A2(I903_2), 
	.A1(I903_1));
   NAND3_X1 U_vsync (.ZN(vsync), 
	.A3(I867), 
	.A2(I855), 
	.A1(I914_1));
   NAND2_X1 U_cblank (.ZN(cblank), 
	.A2(I841), 
	.A1(I928_1));
   NAND4_X1 U_I4 (.ZN(I4), 
	.A4(I266), 
	.A3(I270), 
	.A2(I274), 
	.A1(I278));
   NAND3_X1 U_I884 (.ZN(I884), 
	.A3(I326), 
	.A2(I861), 
	.A1(I1110_1));
   NAND4_X1 U_I5 (.ZN(I5), 
	.A4(I298), 
	.A3(I827), 
	.A2(I889), 
	.A1(I282));
   NAND3_X1 U_csync (.ZN(csync), 
	.A3(I881), 
	.A2(I924_2), 
	.A1(I924_1));
   NAND3_X1 U_I6 (.ZN(I6), 
	.A3(I895), 
	.A2(I899), 
	.A1(I909_1));
   NAND2_X1 U_I2 (.ZN(I2), 
	.A2(I821), 
	.A1(I900_1));
   NAND3_X1 U_I874 (.ZN(I874), 
	.A3(I831), 
	.A2(I863), 
	.A1(I1099_1));
   NAND3_X1 U_I7 (.ZN(I7), 
	.A3(I887), 
	.A2(I782), 
	.A1(I778));
   NOR2_X1 U_I555 (.ZN(I555), 
	.A2(st_1), 
	.A1(st_0));
   NOR2_X1 U_I587 (.ZN(I587), 
	.A2(st_2), 
	.A1(st_1));
   NOR2_X1 U_I595 (.ZN(I595), 
	.A2(st_2), 
	.A1(st_0));
   NOR2_X1 U_I511 (.ZN(I511), 
	.A2(st_5), 
	.A1(st_3));
   NOR2_X1 U_I739 (.ZN(I739), 
	.A2(st_1), 
	.A1(st_5));
   NOR2_X1 U_I627 (.ZN(I627), 
	.A2(I78), 
	.A1(pcnt241));
   NOR2_X1 U_I547 (.ZN(I547), 
	.A2(st_2), 
	.A1(I61));
   NOR2_X1 U_I675 (.ZN(I675), 
	.A2(st_1), 
	.A1(I61));
   NOR2_X1 U_I535 (.ZN(I535), 
	.A2(st_0), 
	.A1(I590));
   NOR2_X1 U_I671 (.ZN(I671), 
	.A2(I59), 
	.A1(I458));
   NOR2_X1 U_I663 (.ZN(I663), 
	.A2(I58), 
	.A1(st_1));
   NOR2_X1 U_I551 (.ZN(I551), 
	.A2(I57), 
	.A1(I61));
   NOR2_X1 U_I583 (.ZN(I583), 
	.A2(I60), 
	.A1(I511));
   NOR2_X1 U_I603 (.ZN(I603), 
	.A2(I56), 
	.A1(I61));
   NOR3_X1 U_I799 (.ZN(I799), 
	.A3(I59), 
	.A2(I58), 
	.A1(I56));
   NOR2_X1 U_I209 (.ZN(I209), 
	.A2(I946_2), 
	.A1(I946_1));
   NOR2_X1 U_I563 (.ZN(I563), 
	.A2(I56), 
	.A1(I578));
   NOR3_X1 U_I795 (.ZN(I795), 
	.A3(I578), 
	.A2(st_2), 
	.A1(st_3));
   NOR2_X1 U_I95 (.ZN(I95), 
	.A2(I591), 
	.A1(I587));
   NOR2_X1 U_I463 (.ZN(I463), 
	.A2(I594), 
	.A1(I458));
   NOR2_X1 U_I131 (.ZN(I131), 
	.A2(I936_2), 
	.A1(I936_1));
   NOR2_X1 U_I455 (.ZN(I455), 
	.A2(I658), 
	.A1(I554));
   NOR2_X1 U_I559 (.ZN(I559), 
	.A2(I56), 
	.A1(I658));
   NOR2_X1 U_I531 (.ZN(I531), 
	.A2(I59), 
	.A1(I574));
   NOR3_X1 U_I787 (.ZN(I787), 
	.A3(I574), 
	.A2(st_5), 
	.A1(I554));
   NOR2_X1 U_I487 (.ZN(I487), 
	.A2(I498), 
	.A1(st_4));
   NOR2_X1 U_I543 (.ZN(I543), 
	.A2(I590), 
	.A1(I742));
   NOR2_X1 U_I747 (.ZN(I747), 
	.A2(I1044_1), 
	.A1(I638));
   NOR2_X1 U_I539 (.ZN(I539), 
	.A2(I60), 
	.A1(I546));
   NOR2_X1 U_I207 (.ZN(I207), 
	.A2(I943_1), 
	.A1(I595));
   NOR3_X1 U_I779 (.ZN(I779), 
	.A3(I638), 
	.A2(st_4), 
	.A1(I95));
   NOR2_X1 U_I259 (.ZN(I259), 
	.A2(I967_1), 
	.A1(st_0));
   NOR2_X1 U_I837 (.ZN(I837), 
	.A2(I1071_1), 
	.A1(I487));
   NOR2_X1 U_I867 (.ZN(I867), 
	.A2(I1089_1), 
	.A1(I834));
   NOR2_X1 U_I615 (.ZN(I615), 
	.A2(st_2), 
	.A1(I475));
   NOR2_X1 U_I827 (.ZN(I827), 
	.A2(I1062_1), 
	.A1(I531));
   NOR2_X1 U_csm (.ZN(csm), 
	.A2(I798), 
	.A1(I555));
   NOR2_X1 U_I213 (.ZN(I213), 
	.A2(I950_2), 
	.A1(I950_1));
   NOR3_X1 U_I877 (.ZN(I877), 
	.A3(I551), 
	.A2(I1102_2), 
	.A1(I1102_1));
   NOR2_X1 U_I823 (.ZN(I823), 
	.A2(I1059_1), 
	.A1(I259));
   NOR2_X1 U_I855 (.ZN(I855), 
	.A2(st_3), 
	.A1(I615));
   NOR2_X1 U_I205 (.ZN(I205), 
	.A2(I940_1), 
	.A1(I563));
   NOR2_X1 U_I841 (.ZN(I841), 
	.A2(I1077_1), 
	.A1(I799));
   NOR2_X1 U_I371 (.ZN(I371), 
	.A2(I988_1), 
	.A1(I68));
   NOR2_X1 U_I731 (.ZN(I731), 
	.A2(I607), 
	.A1(I583));
   NOR2_X1 U_I217 (.ZN(I217), 
	.A2(I954_2), 
	.A1(I954_1));
   NOR2_X1 U_I861 (.ZN(I861), 
	.A2(I1081_2), 
	.A1(I1081_1));
   NOR3_X1 U_I889 (.ZN(I889), 
	.A3(I870), 
	.A2(I1116_2), 
	.A1(I1116_1));
   NOR3_X1 U_I881 (.ZN(I881), 
	.A3(I838), 
	.A2(I1106_2), 
	.A1(I1106_1));
   NOR3_X1 U_I899 (.ZN(I899), 
	.A3(I1123_1), 
	.A2(I347), 
	.A1(I872));
   NOR2_X1 U_I831 (.ZN(I831), 
	.A2(I1065_1), 
	.A1(I371));
   NOR2_X1 U_I895 (.ZN(I895), 
	.A2(I1120_1), 
	.A1(I884));
   NOR2_X1 U_I821 (.ZN(I821), 
	.A2(I1055_2), 
	.A1(I1055_1));
   NOR2_X1 U_I863 (.ZN(I863), 
	.A2(I1085_2), 
	.A1(I1085_1));
   NOR2_X1 U_I887 (.ZN(I887), 
	.A2(I1113_1), 
	.A1(I874));
   SDFF_X1 U_st_5 (.SI(test_si), 
	.SE(test_se), 
	.Q(st_5), 
	.D(I2), 
	.CK(CK));
   SDFF_X1 U_st_4 (.SI(st_5), 
	.SE(test_se), 
	.Q(st_4), 
	.D(I3), 
	.CK(CK));
   SDFF_X1 U_st_3 (.SI(st_4), 
	.SE(test_se), 
	.Q(st_3), 
	.D(I4), 
	.CK(CK));
   SDFF_X1 U_st_2 (.SI(st_3), 
	.SE(test_se), 
	.Q(st_2), 
	.D(I5), 
	.CK(CK));
   SDFF_X1 U_st_1 (.SI(st_2), 
	.SE(test_se), 
	.Q(st_1), 
	.D(I6), 
	.CK(CK));
   SDFF_X1 U_st_0 (.SI(st_1), 
	.SE(test_se), 
	.Q(st_0), 
	.D(I7), 
	.CK(CK));
endmodule

